export const ZH_TW = {
  locale: "zh-TW",
  lang: "zh-Hant-TW",
  localePrefix: "/zh",
  switchLabel: "EN",
  switchAria: "切換至英文版",
  skip: "跳至主要內容",
  name: "邱文昱 Wenyu Chiou",
  initials: "WC",
  nav: [
    { id: "work", label: "專案作品", href: "/work/" },
    { id: "research", label: "研究計畫", href: "/research/" },
    { id: "publications", label: "著作與演講", href: "/publications/" },
    { id: "about", label: "關於我", href: "/about/" },
  ],
  labels: {
    menu: "選單",
    close: "關閉選單",
    theme: "切換色彩主題",
    resume: "履歷",
    contact: "聯絡方式",
    github: "GitHub",
    linkedin: "LinkedIn",
    scholar: "Google Scholar",
    orcid: "ORCID",
    website: "個人網站",
    updated: "更新時間",
    source: "資料來源",
    status: "狀態",
    evidence: "證據",
    limitation: "限制",
    details: "檢視案例研究",
    repository: "原始碼儲存庫",
    publication: "出版物",
    poster: "海報",
    open: "開啟",
    stars: "stars",
    forks: "forks",
    snapshot: "GitHub REST API 資料快照",
  },
  hero: {
    eyebrow: "博士研究員 · 理海大學 (Lehigh University)",
    title: "邱文昱 Wenyu Chiou",
    headline: "以人類行為證據為基礎的 AI 代理，應用於行為與人類—環境模擬。",
    intro: "我評估大型語言模型（LLM）的決策是否與實際測得的人類決策路徑一致，治理代理的行動，並將這些決策與持續變動的物理系統耦合。",
    context: "洪災風險是我用來進行行為模擬、模型評估與代理治理 (agent governance) 的高風險測試場域。",
    primary: { label: "探索研究系統", href: "#observatory" },
    secondary: { label: "檢視精選作品", href: "/work/" },
    availability: "尋求 2027 年夏季實習機會，專注於 LLM 評估、代理系統、行為模擬以及 AI for Science 等領域。",
    imageAlt: "Wenyu Chiou 於 AGU 2025 發表耦合人類與洪災調適模型海報。",
    imageCaption: "於紐奧良舉行的 AGU 2025 發表人類—洪災耦合模型研究。",
  },
  proof: [
    { value: "937", label: "人類樣本數" },
    { value: "52,141", label: "模擬家戶數" },
    { value: "50", label: "FLOODABM 每情境隨機模擬次數" },
    { value: "6K+", label: "GitHub 社群影響力" },
  ],
  observatory: {
    eyebrow: "行為系統觀測站",
    title: "透過完整研究系統追蹤決策",
    intro: "每個階段都揭示了不同的效度問題：測量了什麼、如何估算路徑、模型改變了什麼，以及代理行為可能在何處失效。",
    hint: "展開各階段以檢視其證據、風險與關聯性。",
    fields: { input: "輸入", method: "方法", output: "輸出", risk: "效度風險", teams: "對 AI 團隊的價值" },
    stages: [
      {
        id: "human-evidence",
        number: "01",
        title: "人類證據",
        question: "人們在面臨洪災風險時會採取什麼行動？",
        input: "來自 Passaic 河域調查的 937 戶家戶資料。",
        method: "問卷設計、心理計量學，以及考量次群體差異的測量。",
        output: "基於實測回應的潛在構念與調適選擇。",
        risk: "抽樣、自我報告及建構效度會限制推論的普遍性。",
        relevance: "為 AI 評估提供實證參考，而非僅依賴直覺的評分標準。",
        caseStudy: "/work/human-grounded-llm-evaluation/",
      },
      {
        id: "decision-pathways",
        number: "02",
        title: "決策路徑",
        question: "哪些潛在因素與路徑形塑了調適決策？",
        input: "風險感知、效能、限制、產權以及報告的行動。",
        method: "驗證性因素分析 (CFA) 與多群體結構方程式模型 (SEM)。",
        output: "具解釋力的整體決策路徑與社會群體比較。",
        risk: "模型適配度本身無法確立因果關係。",
        relevance: "將評估方式從單純比對答案，提升為比較決策結構。",
        caseStudy: "/work/human-grounded-llm-evaluation/",
      },
      {
        id: "behavioral-simulation",
        number: "03",
        title: "行為模擬",
        question: "家戶決策如何在時間與空間中累積？",
        input: "基於問卷的代理參數、洪災暴露度以及保險機制。",
        method: "結合巨災模型（catastrophe model）的代理人基模型（ABM）。",
        output: "2011–2023 年間，跨 27 個普查區的 52,141 戶家戶軌跡。",
        risk: "結果取決於校準選擇與情境假設。",
        relevance: "在具有狀態的系統中測試行為，其中選擇會產生下游效應。",
        caseStudy: "/work/floodabm/",
      },
      {
        id: "llm-evaluation",
        number: "04",
        title: "LLM 行為評估",
        question: "生成的決策是否與實測的人類路徑相符？",
        input: "從核可的問卷屬性中衍生出隱藏標籤的人物誌 (personas)。",
        method: "比較人類與 LLM 的路徑，並進行重複執行的穩定性檢查。",
        output: "考量次群體差異的評估設計；論文撰寫中。",
        risk: "流暢的語言可能掩蓋結構上的不一致或不穩定性。",
        relevance: "將表面流暢度與基於證據的行為一致性區分開來。",
        caseStudy: "/work/human-grounded-llm-evaluation/",
      },
      {
        id: "governance-repair",
        number: "05",
        title: "治理與修正",
        question: "代理行動能否通過明確的領域與行為限制？",
        input: "結構化的提案行動、評分與支持理由。",
        method: "解析、物理／財務／行為驗證、針對性修正與稽核軌跡。",
        output: "在狀態更新前，接受、拒絕或修正決策。",
        risk: "規則僅涵蓋已宣告的限制，無法涵蓋現實世界中所有的失敗模式。",
        relevance: "將治理轉化為可檢驗的系統行為，而非只是政策口號。",
        caseStudy: "/work/wagf/",
      },
      {
        id: "external-feedback",
        number: "06",
        title: "外部系統回饋",
        question: "當決策進入耦合環境後，會發生什麼改變？",
        input: "調適行動、危害、財產、保險與財務狀態。",
        method: "確定性狀態轉換與隨機情境系集 (stochastic scenario ensembles)。",
        output: "更新後的暴露度、損害、理賠金與自付額負擔。",
        risk: "回饋品質受限於外部模型與可用數據。",
        relevance: "透過在變動系統中的後果來評估代理，而非僅評估孤立的文本。",
        caseStudy: "/work/floodabm/",
      },
    ],
  },
  flagship: {
    eyebrow: "精選案例研究",
    title: "三個系統，一個研究核心",
    intro: "人類證據是評估的基石，模擬揭示了行為後果，而治理則管控了代理行動何時能改變世界模型。",
    items: [
      {
        slug: "human-grounded-llm-evaluation",
        index: "01",
        title: "以人類行為證據為基礎的 LLM 評估",
        status: "撰寫中",
        line: "比較 LLM 生成決策與實測人類路徑在各社會群體間的差異。",
        metrics: ["937 份樣本", "隱藏標籤人物誌", "CFA + 多群體 SEM"],
        href: "/work/human-grounded-llm-evaluation/",
        accent: "coral",
      },
      {
        slug: "floodabm",
        index: "02",
        title: "FLOODABM",
        status: "研究原型 · 已封存",
        line: "將家戶調適行為與洪災損害、保險及財務風險連結。",
        metrics: ["52,141 個代理", "27 個普查區", "2011–2023 · 每情境 50 次模擬"],
        href: "/work/floodabm/",
        accent: "teal",
      },
      {
        slug: "wagf",
        index: "03",
        title: "WAGF",
        status: "開發中 · 準備釋出",
        line: "在耦合模擬更新前，檢查並修正代理決策。",
        metrics: ["結構化輸出", "限制檢查", "稽核軌跡"],
        href: "/work/wagf/",
        accent: "amber",
      },
    ],
  },
  ledger: {
    eyebrow: "證據總覽",
    title: "狀態也是證據的一部分",
    items: [
      { status: "已發表", title: "Yang & Chiou (2026)", detail: "Water Resources Research, 62(6), e2025WR042111", href: "https://doi.org/10.1029/2025WR042111" },
      { status: "同儕審查後修改中", title: "Household flood adaptation and financial outcomes", detail: "人類—洪災耦合模型分析", href: "/publications/" },
      { status: "撰寫中", title: "Human-grounded LLM behavior study", detail: "考量次群體的決策路徑比較", href: "/work/human-grounded-llm-evaluation/" },
      { status: "持續維護的開源專案", title: "AI 研究與代理工作流工具", detail: "公開儲存庫、測試與發布紀錄", href: "/work/#open-source" },
    ],
  },
  openSource: {
    eyebrow: "開源系統實證",
    title: "具備可檢驗失效行為的研究基礎設施",
    intro: "精選的儲存庫支援研究營運、代理編排與多語言學習。各項數據皆透過經過審查的建置期數據工作流進行更新。",
    repos: [
      { name: "awesome-agentic-ai-zh", key: "awesome-agentic-ai-zh", desc: "維護中的三語 AI 代理發展藍圖，具備自動化跨語言檢查。", href: "https://github.com/WenyuChiou/awesome-agentic-ai-zh" },
      { name: "ai-research-skills", key: "ai-research-skills", desc: "可組合的研究工作流，涵蓋從發現研究缺口到研究設計與草稿撰寫。", href: "https://github.com/WenyuChiou/ai-research-skills" },
      { name: "research-hub", key: "research-hub", desc: "本地優先的 Zotero、Obsidian 與 NotebookLM 工作區，具備來源檢查功能。", href: "https://github.com/WenyuChiou/research-hub" },
      { name: "agent-collab-skills", key: "agent-collab-skills", desc: "多代理協作的任務拆解、協調、辯論與驗收關卡。", href: "https://github.com/WenyuChiou/agent-collab-skills" },
      { name: "codex-delegate", key: "codex-delegate", desc: "跨平台委派封裝工具，透過儲存庫狀態驗證任務完成度。", href: "https://github.com/WenyuChiou/codex-delegate" },
    ],
  },
  talksPreview: {
    eyebrow: "著作與演講",
    title: "同儕審查著作與公開發表",
    link: { label: "檢視完整紀錄", href: "/publications/" },
  },
  updates: {
    eyebrow: "近期公開動態",
    title: "寫作、發布與演講",
    intro: "LinkedIn 貼文經過策展，因為 LinkedIn 並未提供可靠的公開會員貼文存取。GitHub 儲存庫數據由自動化程式更新，並在拉取請求 (pull requests) 中進行審查。",
  },
  workPage: {
    eyebrow: "精選作品",
    title: "基於證據的代理系統",
    intro: "研究工作從實測決策出發，推進至模型結構、代理行為、限制檢查，以及在耦合環境中的結果。",
    supportingTitle: "支援的開源系統",
  },
  researchPage: {
    eyebrow: "研究計畫",
    title: "從人類決策證據到受治理的代理行動",
    intro: "我的研究探討模型生成的行為在何處與觀察到的路徑一致、在何處產生分歧，以及在這些決策影響外部系統之前需要哪些管控。",
    questions: [
      { title: "測量", text: "哪些構念與次群體差異有受到人類回應數據的支持？" },
      { title: "行為一致性", text: "生成的回應是否在重複執行中保留了相關的路徑結構？" },
      { title: "治理", text: "哪些物理、財務與行為限制應該作為代理行動的把關標準？" },
      { title: "耦合", text: "決策如何隨時間改變暴露度、損害、保險以及家戶財務負擔？" },
    ],
    methodsTitle: "方法與系統",
    toolkitLabel: "研究工具包",
    methods: [
      "問卷設計與心理計量測量",
      "驗證性因素分析 (CFA) 與結構方程式模型 (SEM)",
      "考量次群體差異與重複執行的 LLM 評估",
      "代理人基模型（ABM）與巨災模型之耦合",
      "結構化輸出、驗證器、針對性修正與稽核日誌",
      "Python 研究軟體、測試、CI 以及具版本控制的研究產出",
    ],
    limitsTitle: "效度邊界",
    limits: [
      "問卷證據特定於其母體、地點、構念與收集過程。",
      "統計模型的適配度是針對特定結構的證據，而非因果關係的證明。",
      "LLM 回應的一致性不代表代理等同於人類。",
      "治理規則揭露並管控已宣告的限制；無法涵蓋未知的失敗模式。",
      "模擬結果依然受限於模型結構、校準與情境假設。",
    ],
  },
  publicationsPage: {
    eyebrow: "著作與演講",
    title: "研究紀錄",
    intro: "已發表、修改中以及撰寫中的作品均有明確標示。公開連結指向出版商、官方議程、海報或機構紀錄。",
    groups: [
      {
        title: "同儕審查期刊",
        entries: [
          { year: "2026", status: "已發表", title: "Leveraging Large Language Models for Agent-Based Simulation of Human–Water System Interactions", citation: "Yang, Y. C. E., & Chiou, W. Water Resources Research, 62(6), e2025WR042111.", links: [{ label: "DOI", href: "https://doi.org/10.1029/2025WR042111" }, { label: "Scholar 紀錄", href: "https://scholar.google.com/citations?view_op=view_citation&hl=zh-TW&user=vSQ3zT4AAAAJ&citation_for_view=vSQ3zT4AAAAJ:zYLM7Y9cAGgC" }] },
        ],
      },
      {
        title: "論文手稿",
        entries: [
          { year: "Current", status: "同儕審查後修改中", title: "Household Flood Adaptation and Financial Outcomes: A Coupled Human–Flood Modeling Analysis of Homeowners and Renters", citation: "Chiou, W. Y., Yang, Y. C. E., Tanaka, T., Jamrussri, S., & Feng, S. Water Resources Research.", links: [] },
          { year: "Current", status: "撰寫中", title: "Flood Adaptation Decision Variables and Pathways across Social Groups: A Comparison between Human Survey Responses and Responses Generated by Large Language Models", citation: "Chiou, W. Y. Planned submission to Progress in Disaster Science.", links: [{ label: "研究總覽", href: "/work/human-grounded-llm-evaluation/" }] },
        ],
      },
      {
        title: "會議發表",
        entries: [
          { year: "2026", status: "論文發表", title: "What Makes AI Believable? Comparing AI and Human Responses in Mental Health Risk Assessment", citation: "Chiou, W., & Chiou, H. 2026 ISDSA Meeting on Data Science and Analytics, Beijing, China, July 28–31, 2026.", links: [{ label: "機構紀錄", href: "https://www.mgt.ntnu.edu.tw/%E9%82%B1%E7%9A%93%E6%94%BF" }] },
          { year: "2025", status: "海報發表", title: "Modeling Long-Term Flood Adaptation Action Across Marginalized and Non-Marginalized Groups: A Coupled Agent-Based Model", citation: "Chiou, W., Yang, Y. C. E., Tanaka, T., Jamrussri, S., & Feng, S. AGU25, New Orleans. Abstract 1890827; poster NH41E-0449.", links: [{ label: "官方議程", href: "https://agu.confex.com/agu/f/ScienceNexusAGU25" }, { label: "海報 PDF", href: "/assets/AGU2025_poster_Wenyu_Chiou.pdf" }] },
          { year: "2025", status: "口頭發表 38-03", title: "Investigating the Decision-Making Process and Causal Relationships between Flood Risk Perception and Adaptation Actions", citation: "The 2nd International Sociohydrology Conference, Tokyo, Japan.", links: [] },
          { year: "2023", status: "會議摘要", title: "Submarine groundwater discharge study combining electrical resistivity tomography, field observation, and numerical simulation", citation: "AGU Fall Meeting 2023.", links: [] },
        ],
      },
    ],
  },
  aboutPage: {
    eyebrow: "關於我",
    title: "致力於人類、代理與實體系統交界的研究工程師",
    bio: [
      "我是理海大學 (Lehigh University) 土木與環境工程系的博士候選人，在複雜適應水系統實驗室 (Complex Adaptive Water Systems Lab) 進行研究。我的工作結合了計算社會科學、代理人基模型、LLM 評估以及研究軟體工程。",
      "我的研究起點是人類行為與人類—水系統的實證研究：問卷設計、心理計量學，以及人類—洪災耦合風險模擬。這些基礎現在指引了我如何評估模型生成的行為，並設計具備限制檢查的代理系統。",
      "我關注能揭示分歧、不穩定性與極限的評估方式。目標不是宣稱代理等同於人類；而是讓證據、模型行為與下游後果之間的關聯變得可受檢驗。",
    ],
    educationTitle: "學歷",
    education: [
      { degree: "土木與環境工程博士（Ph.D.）", school: "理海大學（Lehigh University）", date: "2024–至今（預計 2027 年 12 月畢業）" },
      { degree: "水文與海洋科學碩士 (M.S.)", school: "國立中央大學", date: "2021–2023" },
      { degree: "地球科學學士 (B.S.)", school: "國立中央大學", date: "2017–2021" },
    ],
    trajectoryTitle: "經歷軌跡",
    timelineLabel: "時間軸",
    trajectory: [
      { year: "2020–2023", text: "在台灣進行野外、同位素、地下水與氣候數據研究。" },
      { year: "2024–2025", text: "基於問卷的行為建模，以及家戶洪災耦合模擬。" },
      { year: "2025–至今", text: "以人類行為證據為基礎的 LLM 評估、代理治理以及研究工作流系統。" },
    ],
  },
  caseStudies: {
    "human-grounded-llm-evaluation": {
      eyebrow: "案例研究 01 · LLM 行為評估",
      title: "以人類行為證據為基礎的 LLM 評估",
      status: "撰寫中",
      lede: "一項考量次群體差異的研究，探討 LLM 生成的洪災調適回應是否與 937 戶家戶實測的決策路徑相符。",
      problem: "流暢的回應可能看似合理，卻保留了錯誤的風險感知、效能、限制與行動間的關聯。本研究評估的是結構，而不僅僅是表面的相似度。",
      relevance: "同樣的問題也出現在模擬使用者研究、客服代理、健康風險評估與政策模擬中：輸出結果可能聽起來像人類，但行為上卻與實測證據不一致。",
      role: "我設計了人類與 LLM 的對比評估、準備了隱藏標籤的人物誌、規劃了心理計量與多群體 SEM 比較，並建置了重複執行的穩定性檢查。",
      scale: ["937 份核可的人類樣本", "整體與社會群體視角", "重複執行的穩定性設計"],
      method: ["將核可的問卷屬性映射至隱藏群體標籤的人物誌中。", "在固定協議下收集結構化的生成回應。", "運用相同的核可測量邏輯估算構念與路徑結構。", "在不宣稱人類等效性的前提下，比較整體、次群體與重複執行的行為。"],
      artifact: "公開的圖表為研究設計示意圖。數據比較結果尚未發表，故刻意省略。",
      validation: ["人類與生成回應間相同的構念定義", "考量次群體的比較", "重複執行的穩定性檢查", "明確的手稿與結果狀態"],
      limitations: ["問卷回應為自我報告且具備情境特異性。", "人物誌提示詞無法編碼所有社會或情境因素。", "路徑一致性不能作為 LLM 能替代人類的證據。", "未發表的效應值與次群體結果未予展示。"],
      learned: "當比較的單位是具有明確效度限制的決策路徑，而非單一的合理答案時，行為評估會變得更有價值。",
      links: [{ label: "研究計畫", href: "/research/" }, { label: "著作與演講", href: "/publications/" }],
      interaction: "pathways",
    },
    floodabm: {
      eyebrow: "案例研究 02 · 耦合模擬",
      title: "FLOODABM",
      status: "研究原型 · 已封存",
      lede: "涵蓋紐澤西州 27 個普查區的 52,141 戶家戶代理人基模型，並與災難、保險及財務機制進行耦合。",
      problem: "洪災調適決策對各家戶損失的改變並不平均。一個有用的模型必須能隨時間將行為路徑與危害、財產、保險及自付額結果連結起來。",
      relevance: "對 AI 團隊而言，FLOODABM 是一個具備狀態的評估環境：決策會更新外部系統，後果會累積，且模型的假設保持清晰可見。",
      role: "我設計並執行了 937 戶問卷調查、將路徑轉換為代理參數、建置了家戶模擬，並將其與災難及 NFIP (國家洪災保險計畫) 機制進行耦合。",
      scale: ["52,141 戶家戶", "27 個普查區", "2011–2023", "每情境 50 次隨機模擬"],
      method: ["透過 SEM 與貝氏校準確立基於問卷的行為參數。", "在年度時間步長中推進家戶調適與保險決策。", "將代理與洪災危害、財產損害、NFIP 保費/理賠金/自付額及財務狀態耦合。", "為每個情境執行 50 次隨機實現並報告聚合分佈。"],
      artifact: "AGU 2025 海報與已封存的儲存庫記錄了耦合架構與總體結果。",
      validation: ["基於問卷的行為參數", "情境系集", "多層次診斷", "封存的程式碼與引用元數據"],
      limitations: ["校準與問卷證據特定於地點與時期。", "家戶代理簡化了決策過程與社會脈絡。", "危害與財務輸出繼承了來自耦合模型的不確定性。", "情境結果不應視為對個別家戶的預測。"],
      learned: "將行為與實體及財務回饋耦合，使得假設可被稽核，並揭露了看似合理的行動可能在何處造成不公平的後果。",
      links: [{ label: "GitHub 儲存庫", href: "https://github.com/WenyuChiou/FLOODABM" }, { label: "AGU 海報", href: "/assets/AGU2025_poster_Wenyu_Chiou.pdf" }],
      interaction: "timeline",
    },
    wagf: {
      eyebrow: "案例研究 03 · 代理治理",
      title: "WAGF",
      status: "開發中 · 準備釋出",
      lede: "水資源代理治理框架（Water Agent Governance Framework），在 LLM 代理決策更新人類—水系統模擬之前進行檢查。此框架尚未公開釋出。",
      problem: "語法上有效的行動，仍可能違反物理限制、家戶財務、行為理論或當前的模擬狀態。",
      relevance: "此治理模式可轉移至任何具備狀態的代理系統，在執行前行動必須滿足明確的限制並留下稽核軌跡。",
      role: "我設計了上下文建構器、結構化決策綱要、解析器、驗證器、針對性修正迴圈、稽核紀錄以及模擬狀態邊界。",
      scale: ["結構化決策契約", "實體 + 財務 + 行為檢查", "確定性稽核軌跡"],
      method: ["從核可的人物設定與模擬狀態中建構脈絡。", "要求結構化的行動與評分。", "在任何狀態改變前進行解析。", "執行物理、財務與行為理論檢查。", "接受、拒絕或要求針對性修正。", "寫入軌跡，僅在行動被接受後更新狀態。"],
      artifact: "公開的治理軌跡是控制流的靜態展示。它並未呼叫即時模型，也不是已發布的產品基準測試。",
      validation: ["綱要驗證", "預設阻擋的解析器邊界 (Fail-closed parser boundary)", "具名的規則結果", "確定性展示軌跡", "狀態更新發生在接受之後"],
      limitations: ["已宣告的規則無法涵蓋所有失敗模式。", "修正可能滿足規則但仍產生脆弱的決策。", "該框架仍在開發中，尚未公開釋出。", "展示紀錄僅供說明，並非研究結果。"],
      learned: "當每個決策都揭露了提案、失敗的規則、允許的修正以及確切的狀態轉換時，治理才能最為清晰。",
      links: [{ label: "研究計畫", href: "/research/" }, { label: "聯繫討論研究", href: "mailto:wec324@lehigh.edu" }],
      interaction: "governance",
    },
  },
  caseLabels: {
    problem: "問題",
    why: "為何此問題重要",
    aiTeams: "對 AI 團隊的價值",
    artifact: "系統產出",
    inspect: "檢視研究邏輯",
    roleMethod: "角色與方法",
    built: "我建置了什麼",
    validation: "驗證與限制",
    validationShort: "驗證",
    limitations: "限制",
    changed: "帶來了什麼改變",
  },
  documents: {
    title: "文件",
    intro: "請依據您的情境選擇文件。網站保持統一的定位；而 PDF 則針對不同讀者調整重點。",
    items: [
      { label: "業界履歷 · 英文", href: "/assets/Wenyu_Chiou_Industry_Resume_EN.pdf", type: "PDF" },
      { label: "業界履歷 · 繁中", href: "/assets/Wenyu_Chiou_Industry_Resume_zh-TW.pdf", type: "PDF" },
      { label: "學術 CV · 英文", href: "/assets/Wenyu_Chiou_Academic_CV_EN.pdf", type: "PDF" },
      { label: "學術 CV · 繁中", href: "/assets/Wenyu_Chiou_Academic_CV_zh-TW.pdf", type: "PDF" },
    ],
  },
  contact: {
    eyebrow: "聯絡方式",
    title: "建立將模型行為與真實證據連結的評估",
    text: "我正在尋求 2027 年夏季（約 5 月下旬至 8 月中旬）的全職實習機會。我對 LLM 評估、代理系統、行為模擬以及 AI for Science 特別感興趣。",
    email: "wec324@lehigh.edu",
    workAuth: "F-1 學生身分 · 具備 CPT 資格",
    links: [
      { label: "GitHub", href: "https://github.com/WenyuChiou" },
      { label: "LinkedIn", href: "https://www.linkedin.com/in/wenyu-chiou" },
      { label: "Google Scholar", href: "https://scholar.google.com/citations?user=vSQ3zT4AAAAJ&hl=en" },
      { label: "ORCID", href: "https://orcid.org/0009-0005-8006-1288" },
    ],
  },
  footer: {
    line: "以人類行為證據為基礎的 LLM 評估 · 代理治理 · 行為模擬",
    note: "建置為靜態、無障礙的研究紀錄。",
  },
  interactions: {
    pathways: {
      overall: "整體研究",
      owners: "屋主視角",
      renters: "租客視角",
      controlLabel: "路徑比較視角",
      lensLabel: "此視角的重點",
      views: {
        overall: "將完整路徑結構與以問卷為基礎的參照進行比較。",
        owners: "在不向模型揭露社會群體標籤的前提下，檢視屋主路徑。",
        renters: "使用相同的測量構念，檢視租客路徑與限制條件相關差異。",
      },
      note: "研究設計示意圖 · 未包含未發表的係數",
      input: "人物誌輸入",
      constructs: "測量構念",
      pathways: "路徑比較",
      stability: "重複執行穩定性",
    },
    timeline: {
      owner: "屋主",
      renter: "租客",
      controlLabel: "家戶租賃身分視角",
      lensLabel: "此視角中的變化",
      views: {
        owner: "屋主狀態包含房產調適、保險、損害、理賠與自付額回饋。",
        renter: "租客狀態採用符合租賃身分的選擇與財務曝險，不預設可執行房產層級行動。",
      },
      note: "系統架構示意圖 · 並非已報告的研究結果",
      start: "家戶狀態",
      choice: "調適選擇",
      hazard: "洪災事件",
      finance: "損害、理賠與自付額更新",
      repeat: "下一個年度時間步長",
    },
    governance: {
      controlLabel: "治理流程狀態",
      first: "檢視提案行動",
      repaired: "檢視針對性修正",
      note: "靜態展示 · 無即時模型呼叫",
      proposal: "提案行動",
      parse: "解析器",
      physical: "實體檢查",
      financial: "財務檢查",
      behavioral: "行為檢查",
      audit: "稽核紀錄",
      update: "狀態更新",
      failed: "已拒絕：成本超出家戶可用預算",
      passed: "修正後接受：成本已降至宣告的預算內",
      blocked: "已阻擋",
      accepted: "已接受",
    }
  }
};
