export const EN = {
  locale: "en",
  lang: "en",
  localePrefix: "",
  switchLabel: "繁中",
  switchAria: "Switch to Traditional Chinese",
  skip: "Skip to content",
  name: "Wenyu Chiou",
  initials: "WC",
  nav: [
    { id: "work", label: "Work", href: "/work/" },
    { id: "research", label: "Research", href: "/research/" },
    { id: "publications", label: "Publications & Talks", href: "/publications/" },
    { id: "about", label: "About", href: "/about/" },
  ],
  labels: {
    menu: "Menu",
    close: "Close menu",
    theme: "Toggle color theme",
    resume: "Resume",
    contact: "Contact",
    github: "GitHub",
    linkedin: "LinkedIn",
    scholar: "Google Scholar",
    orcid: "ORCID",
    website: "Website",
    updated: "Updated",
    source: "Source",
    status: "Status",
    evidence: "Evidence",
    limitation: "Limitation",
    details: "View case study",
    repository: "Repository",
    publication: "Publication",
    poster: "Poster",
    open: "Open",
    stars: "stars",
    forks: "forks",
    snapshot: "GitHub REST API snapshot",
  },
  hero: {
    eyebrow: "Ph.D. Researcher · Lehigh University",
    title: "Wenyu Chiou",
    headline: "Human-grounded AI agents for behavioral and human–environment simulation.",
    intro: "I evaluate whether LLM decisions align with measured human pathways, govern how agents act, and couple those decisions to evolving physical systems.",
    context: "Flood risk is my high-stakes testbed for behavioral simulation, model evaluation, and agent governance.",
    primary: { label: "Explore the research system", href: "#observatory" },
    secondary: { label: "View selected work", href: "/work/" },
    availability: "Open to Summer 2027 internships in LLM evaluation, agent systems, behavioral simulation, and AI for science.",
    imageAlt: "Wenyu Chiou beside his coupled flood-adaptation modeling poster at AGU 2025.",
    imageCaption: "Presenting coupled human–flood modeling at AGU 2025, New Orleans.",
  },
  proof: [
    { value: "937", label: "human profiles" },
    { value: "52,141", label: "simulated households" },
    { value: "50", label: "runs per FLOODABM scenario" },
    { value: "6K+", label: "GitHub community proof" },
  ],
  observatory: {
    eyebrow: "The Behavioral Systems Observatory",
    title: "Follow a decision through the full research system",
    intro: "Each stage exposes a different validity question: what was measured, how pathways were estimated, what the model changes, and where agent behavior can fail.",
    hint: "Open a stage to inspect its evidence, risk, and relevance.",
    fields: { input: "Input", method: "Method", output: "Output", risk: "Validity risk", teams: "For AI teams" },
    stages: [
      {
        id: "human-evidence",
        number: "01",
        title: "Human evidence",
        question: "What do people report doing under flood risk?",
        input: "937 household profiles from the Passaic River Basin survey.",
        method: "Survey design, psychometrics, and subgroup-aware measurement.",
        output: "Observed constructs and adaptation choices grounded in measured responses.",
        risk: "Sampling, self-report, and construct validity limit generalization.",
        relevance: "Gives AI evaluation an empirical reference instead of an intuition-only rubric.",
        caseStudy: "/work/human-grounded-llm-evaluation/",
      },
      {
        id: "decision-pathways",
        number: "02",
        title: "Decision pathways",
        question: "Which latent factors and pathways shape adaptation decisions?",
        input: "Risk perception, efficacy, constraints, tenure, and reported actions.",
        method: "Confirmatory factor analysis and multi-group structural equation modeling.",
        output: "Interpretable pathway structures for overall and social-group comparisons.",
        risk: "Model fit does not establish causal identification by itself.",
        relevance: "Moves evaluation from matching answers to comparing decision structure.",
        caseStudy: "/work/human-grounded-llm-evaluation/",
      },
      {
        id: "behavioral-simulation",
        number: "03",
        title: "Behavioral simulation",
        question: "How do household decisions accumulate over time and space?",
        input: "Survey-grounded agent parameters, flood exposure, and insurance mechanics.",
        method: "Agent-based modeling coupled to a catastrophe model.",
        output: "52,141 household trajectories across 27 census tracts, 2011–2023.",
        risk: "Results depend on calibration choices and scenario assumptions.",
        relevance: "Tests behavior in a stateful system where choices create downstream effects.",
        caseStudy: "/work/floodabm/",
      },
      {
        id: "llm-evaluation",
        number: "04",
        title: "LLM behavior evaluation",
        question: "Do generated decisions correspond to measured human pathways?",
        input: "Label-blind personas derived from approved survey attributes.",
        method: "Human-versus-LLM pathway comparison with repeated-run stability checks.",
        output: "A subgroup-aware evaluation design; manuscript in preparation.",
        risk: "Plausible language can mask structural disagreement or instability.",
        relevance: "Separates surface fluency from evidence-grounded behavioral correspondence.",
        caseStudy: "/work/human-grounded-llm-evaluation/",
      },
      {
        id: "governance-repair",
        number: "05",
        title: "Governance and repair",
        question: "Can an agent action pass explicit domain and behavioral constraints?",
        input: "Structured proposed actions, ratings, and supporting rationale.",
        method: "Parsing, physical/financial/behavioral validation, targeted repair, and audit traces.",
        output: "Accepted, rejected, or repaired decisions before state updates.",
        risk: "Rules cover declared constraints, not every real-world failure mode.",
        relevance: "Turns governance into inspectable system behavior instead of a policy slogan.",
        caseStudy: "/work/wagf/",
      },
      {
        id: "external-feedback",
        number: "06",
        title: "External-system feedback",
        question: "What changes after a decision enters the coupled environment?",
        input: "Adaptation action, hazard, property, insurance, and financial state.",
        method: "Deterministic state transitions and stochastic scenario ensembles.",
        output: "Updated exposure, damage, payout, and out-of-pocket burden.",
        risk: "Feedback quality is bounded by the external models and available data.",
        relevance: "Evaluates agents by consequences in a changing system, not isolated text.",
        caseStudy: "/work/floodabm/",
      },
    ],
  },
  flagship: {
    eyebrow: "Flagship case studies",
    title: "Three systems, one research argument",
    intro: "Human evidence anchors the evaluation, simulation exposes consequences, and governance controls when an agent action can change the world model.",
    items: [
      {
        slug: "human-grounded-llm-evaluation",
        index: "01",
        title: "Human-Grounded LLM Evaluation",
        status: "In preparation",
        line: "Compare LLM-generated decisions with measured human pathways across social groups.",
        metrics: ["937 profiles", "label-blind personas", "CFA + multi-group SEM"],
        href: "/work/human-grounded-llm-evaluation/",
        accent: "coral",
      },
      {
        slug: "floodabm",
        index: "02",
        title: "FLOODABM",
        status: "Research prototype · archived",
        line: "Connect household adaptation to flood damage, insurance, and financial exposure.",
        metrics: ["52,141 agents", "27 tracts", "2011–2023 · 50 runs/scenario"],
        href: "/work/floodabm/",
        accent: "teal",
      },
      {
        slug: "wagf",
        index: "03",
        title: "WAGF",
        status: "In preparation for release",
        line: "Check and repair agent decisions before they update a coupled simulation.",
        metrics: ["structured output", "constraint checks", "audit trace"],
        href: "/work/wagf/",
        accent: "amber",
      },
    ],
  },
  ledger: {
    eyebrow: "Evidence ledger",
    title: "Status is part of the evidence",
    items: [
      { status: "Published", title: "Yang & Chiou (2026)", detail: "Water Resources Research, 62(6), e2025WR042111", href: "https://doi.org/10.1029/2025WR042111" },
      { status: "Under revision following peer review", title: "Household flood adaptation and financial outcomes", detail: "Coupled human–flood modeling analysis", href: "/publications/" },
      { status: "In preparation", title: "Human-grounded LLM behavior study", detail: "Subgroup-aware pathway comparison", href: "/work/human-grounded-llm-evaluation/" },
      { status: "Maintained open source", title: "AI research and agent workflow tooling", detail: "Public repositories, tests, and release histories", href: "/work/#open-source" },
    ],
  },
  openSource: {
    eyebrow: "Open-source systems proof",
    title: "Research infrastructure with inspectable failure behavior",
    intro: "Selected repositories support research operations, agent orchestration, and multilingual learning. Counts are refreshed through a reviewed build-time data workflow.",
    repos: [
      { name: "awesome-agentic-ai-zh", key: "awesome-agentic-ai-zh", desc: "Maintained trilingual roadmap for agentic AI, with automated cross-language checks.", href: "https://github.com/WenyuChiou/awesome-agentic-ai-zh" },
      { name: "ai-research-skills", key: "ai-research-skills", desc: "Composable research workflow from gap discovery through study design and drafting.", href: "https://github.com/WenyuChiou/ai-research-skills" },
      { name: "research-hub", key: "research-hub", desc: "Local-first Zotero, Obsidian, and NotebookLM workspace with provenance checks.", href: "https://github.com/WenyuChiou/research-hub" },
      { name: "agent-collab-skills", key: "agent-collab-skills", desc: "Task splitting, reconciliation, debate, and acceptance gates for multi-agent work.", href: "https://github.com/WenyuChiou/agent-collab-skills" },
      { name: "codex-delegate", key: "codex-delegate", desc: "Cross-platform delegation wrapper that verifies completion from repository state.", href: "https://github.com/WenyuChiou/codex-delegate" },
    ],
  },
  talksPreview: {
    eyebrow: "Publications and talks",
    title: "Peer-reviewed work and public presentations",
    link: { label: "View the complete record", href: "/publications/" },
  },
  updates: {
    eyebrow: "Recent public updates",
    title: "Writing, releases, and presentations",
    intro: "LinkedIn posts are curated because LinkedIn does not provide reliable public member-post access. GitHub repository metrics are refreshed by automation and reviewed in pull requests.",
  },
  workPage: {
    eyebrow: "Selected work",
    title: "Evidence-grounded agent systems",
    intro: "The work moves from measured decisions to model structure, agent behavior, constraint checks, and consequences in a coupled environment.",
    supportingTitle: "Supporting open-source systems",
  },
  researchPage: {
    eyebrow: "Research program",
    title: "From human decision evidence to governed agent action",
    intro: "My research asks where model-generated behavior corresponds to observed pathways, where it diverges, and what controls are needed before those decisions affect an external system.",
    questions: [
      { title: "Measurement", text: "Which constructs and subgroup differences are supported by human response data?" },
      { title: "Behavioral correspondence", text: "Do generated responses preserve relevant pathway structure across repeated runs?" },
      { title: "Governance", text: "Which physical, financial, and behavioral constraints should gate an agent action?" },
      { title: "Coupling", text: "How do decisions alter exposure, damage, insurance, and household financial burden over time?" },
    ],
    methodsTitle: "Methods and systems",
    toolkitLabel: "Research toolkit",
    methods: [
      "Survey design and psychometric measurement",
      "Confirmatory factor analysis and structural equation modeling",
      "Subgroup-aware and repeated-run LLM evaluation",
      "Agent-based and catastrophe-model coupling",
      "Structured outputs, validators, targeted repair, and audit logs",
      "Python research software, tests, CI, and versioned research artifacts",
    ],
    limitsTitle: "Validity boundaries",
    limits: [
      "Survey evidence is specific to its population, place, constructs, and collection process.",
      "Statistical model fit is evidence about a specified structure, not proof of causality.",
      "LLM response correspondence does not make an agent equivalent to a person.",
      "Governance rules expose and control declared constraints; they cannot cover unknown failure modes.",
      "Simulation results remain conditional on model structure, calibration, and scenario assumptions.",
    ],
  },
  publicationsPage: {
    eyebrow: "Publications & talks",
    title: "Research record",
    intro: "Published, under revision, and in-preparation work is labeled explicitly. Public links point to the publisher, official program, poster, or institutional record.",
    groups: [
      {
        title: "Peer-reviewed",
        entries: [
          { year: "2026", status: "Published", title: "Leveraging Large Language Models for Agent-Based Simulation of Human–Water System Interactions", citation: "Yang, Y. C. E., & Chiou, W. Water Resources Research, 62(6), e2025WR042111.", links: [{ label: "DOI", href: "https://doi.org/10.1029/2025WR042111" }, { label: "Scholar record", href: "https://scholar.google.com/citations?view_op=view_citation&hl=zh-TW&user=vSQ3zT4AAAAJ&citation_for_view=vSQ3zT4AAAAJ:zYLM7Y9cAGgC" }] },
        ],
      },
      {
        title: "Manuscripts",
        entries: [
          { year: "Current", status: "Under revision following peer review", title: "Household Flood Adaptation and Financial Outcomes: A Coupled Human–Flood Modeling Analysis of Homeowners and Renters", citation: "Chiou, W. Y., Yang, Y. C. E., Tanaka, T., Jamrussri, S., & Feng, S. Water Resources Research.", links: [] },
          { year: "Current", status: "In preparation", title: "Flood Adaptation Decision Variables and Pathways across Social Groups: A Comparison between Human Survey Responses and Responses Generated by Large Language Models", citation: "Chiou, W. Y. Planned submission to Progress in Disaster Science.", links: [{ label: "Study overview", href: "/work/human-grounded-llm-evaluation/" }] },
        ],
      },
      {
        title: "Conference presentations",
        entries: [
          { year: "2026", status: "Paper presentation", title: "What Makes AI Believable? Comparing AI and Human Responses in Mental Health Risk Assessment", citation: "Chiou, W., & Chiou, H. 2026 ISDSA Meeting on Data Science and Analytics, Beijing, China, July 28–31, 2026.", links: [{ label: "Institutional record", href: "https://www.mgt.ntnu.edu.tw/%E9%82%B1%E7%9A%93%E6%94%BF" }] },
          { year: "2025", status: "Poster", title: "Modeling Long-Term Flood Adaptation Action Across Marginalized and Non-Marginalized Groups: A Coupled Agent-Based Model", citation: "Chiou, W., Yang, Y. C. E., Tanaka, T., Jamrussri, S., & Feng, S. AGU25, New Orleans. Abstract 1890827; poster NH41E-0449.", links: [{ label: "Official program", href: "https://agu.confex.com/agu/f/ScienceNexusAGU25" }, { label: "Poster PDF", href: "/assets/AGU2025_poster_Wenyu_Chiou.pdf" }] },
          { year: "2025", status: "Oral presentation 38-03", title: "Investigating the Decision-Making Process and Causal Relationships between Flood Risk Perception and Adaptation Actions", citation: "The 2nd International Sociohydrology Conference, Tokyo, Japan.", links: [] },
          { year: "2023", status: "Conference abstract", title: "Submarine groundwater discharge study combining electrical resistivity tomography, field observation, and numerical simulation", citation: "AGU Fall Meeting 2023.", links: [] },
        ],
      },
    ],
  },
  aboutPage: {
    eyebrow: "About",
    title: "A research engineer working across people, agents, and physical systems",
    bio: [
      "I am a Ph.D. candidate in Civil & Environmental Engineering at Lehigh University, advised within the Complex Adaptive Water Systems Lab. My work combines computational social science, agent-based modeling, LLM evaluation, and research software engineering.",
      "I began with empirical human behavior and human–water systems: survey design, psychometrics, and coupled flood-risk simulation. That foundation now informs how I evaluate generated behavior and design constraint-checked agent systems.",
      "I care about evaluation that reveals disagreement, instability, and limits. The goal is not to claim that an agent is a person; it is to make the relationship between evidence, model behavior, and downstream consequences inspectable.",
    ],
    educationTitle: "Education",
    education: [
      { degree: "Ph.D., Civil & Environmental Engineering", school: "Lehigh University", date: "2024–Dec 2027 (expected)" },
      { degree: "M.S., Hydrological and Oceanic Sciences", school: "National Central University", date: "2021–2023" },
      { degree: "B.S., Earth Sciences", school: "National Central University", date: "2017–2021" },
    ],
    trajectoryTitle: "Trajectory",
    timelineLabel: "Timeline",
    trajectory: [
      { year: "2020–2023", text: "Field, isotope, groundwater, and climate-data research in Taiwan." },
      { year: "2024–2025", text: "Survey-grounded behavioral modeling and coupled household flood simulation." },
      { year: "2025–present", text: "Human-grounded LLM evaluation, governed agents, and research workflow systems." },
    ],
  },
  caseStudies: {
    "human-grounded-llm-evaluation": {
      eyebrow: "Case study 01 · LLM behavior evaluation",
      title: "Human-Grounded LLM Evaluation",
      status: "In preparation",
      lede: "A subgroup-aware study of whether LLM-generated flood-adaptation responses correspond to decision pathways measured in 937 household profiles.",
      problem: "Fluent responses can look plausible while preserving the wrong relationships among risk perception, efficacy, constraints, and action. The study evaluates structure, not just surface similarity.",
      relevance: "The same problem appears in simulated-user research, customer agents, health-risk assessment, and policy modeling: an output can sound human without behaving consistently with measured evidence.",
      role: "I designed the human-versus-LLM evaluation, prepared label-blind personas, specified the psychometric and multi-group SEM comparison, and built repeated-run stability checks.",
      scale: ["937 approved human profiles", "overall and social-group lenses", "repeated-run stability design"],
      method: ["Map approved survey attributes into personas without group labels.", "Collect structured generated responses under a fixed protocol.", "Estimate construct and pathway structure with the same approved measurement logic.", "Compare overall, subgroup, and repeated-run behavior without claiming human equivalence."],
      artifact: "The public diagram is a study-design schematic. Numeric comparison results remain unpublished and are intentionally omitted.",
      validation: ["Same construct definitions across human and generated responses", "Subgroup-aware comparison", "Repeated-run stability checks", "Explicit manuscript and result status"],
      limitations: ["Survey responses are self-reported and context-specific.", "Persona prompts cannot encode every social or situational factor.", "Pathway correspondence is not evidence that an LLM is a human substitute.", "Unpublished effect sizes and subgroup results are not shown."],
      learned: "Behavioral evaluation becomes more useful when the unit of comparison is a decision pathway with declared validity limits, rather than one plausible answer.",
      links: [{ label: "Research program", href: "/research/" }, { label: "Publications", href: "/publications/" }],
      interaction: "pathways",
    },
    floodabm: {
      eyebrow: "Case study 02 · Coupled simulation",
      title: "FLOODABM",
      status: "Research prototype · archived",
      lede: "A 52,141-household agent-based model coupled to catastrophe, insurance, and financial mechanics across 27 New Jersey census tracts.",
      problem: "Flood adaptation decisions change losses unevenly across households. A useful model must connect behavioral pathways to hazard, property, insurance, and out-of-pocket outcomes over time.",
      relevance: "For AI teams, FLOODABM is a stateful evaluation environment: decisions update an external system, consequences accumulate, and model assumptions remain visible.",
      role: "I designed and fielded the 937-household survey, translated pathways into agent parameters, built the household simulation, and coupled it to catastrophe and NFIP mechanics.",
      scale: ["52,141 households", "27 census tracts", "2011–2023", "50 stochastic runs per scenario"],
      method: ["Survey-ground behavioral parameters through SEM and Bayesian calibration.", "Advance household adaptation and insurance decisions over annual time steps.", "Couple agents to flood hazard, property damage, NFIP premium/payout/deductible, and financial state.", "Run 50 stochastic realizations for each scenario and report aggregate distributions."],
      artifact: "The AGU 2025 poster and archived repository document the coupled architecture and aggregate outcomes.",
      validation: ["Survey-grounded behavioral parameters", "Scenario ensembles", "Multi-level diagnostics", "Archived code and citation metadata"],
      limitations: ["Calibration and survey evidence are place- and period-specific.", "Household agents simplify decision processes and social context.", "Hazard and financial outputs inherit uncertainty from coupled models.", "Scenario results should not be treated as forecasts for an individual household."],
      learned: "Coupling behavior to physical and financial feedback makes assumptions auditable and exposes where a seemingly reasonable action creates uneven consequences.",
      links: [{ label: "GitHub repository", href: "https://github.com/WenyuChiou/FLOODABM" }, { label: "AGU poster", href: "/assets/AGU2025_poster_Wenyu_Chiou.pdf" }],
      interaction: "timeline",
    },
    wagf: {
      eyebrow: "Case study 03 · Governed agents",
      title: "WAGF",
      status: "In preparation for release",
      lede: "A Water Agent Governance Framework that checks proposed LLM-agent decisions before they update a human–water simulation.",
      problem: "A syntactically valid action can still violate physical limits, household finances, behavioral theory, or the current simulation state.",
      relevance: "The governance pattern transfers to any stateful agent system where an action must satisfy explicit constraints and leave an audit trail before execution.",
      role: "I designed the context builder, structured decision schema, parser, validators, targeted repair loop, audit record, and simulation-state boundary.",
      scale: ["structured decision contract", "physical + financial + behavioral checks", "deterministic audit trace"],
      method: ["Build context from approved persona and simulation state.", "Require a structured action and ratings.", "Parse before any state mutation.", "Run physical, financial, and behavioral-theory checks.", "Accept, reject, or request targeted repair.", "Write the trace, then update state only for an accepted action."],
      artifact: "The public governance trace is a frozen demonstration of the control flow. It does not call a live model and is not a released product benchmark.",
      validation: ["Schema validation", "Fail-closed parser boundary", "Named rule results", "Deterministic demonstration trace", "State update occurs after acceptance"],
      limitations: ["Declared rules cannot cover every failure mode.", "Repair can satisfy a rule while still producing a weak decision.", "The framework remains in preparation for release.", "Demonstration records are illustrative, not research outcomes."],
      learned: "Governance is clearest when every decision exposes the proposal, the rule that failed, the allowed repair, and the exact state transition.",
      links: [{ label: "Research program", href: "/research/" }, { label: "Contact for research discussion", href: "mailto:wec324@lehigh.edu" }],
      interaction: "governance",
    },
  },
  caseLabels: {
    problem: "Problem",
    why: "Why this problem matters",
    aiTeams: "For AI teams",
    artifact: "System artifact",
    inspect: "Inspect the research logic",
    roleMethod: "Role & method",
    built: "What I built",
    validation: "Validation and limitations",
    validationShort: "Validation",
    limitations: "Limitations",
    changed: "What changed",
  },
  interactions: {
    pathways: {
      overall: "Overall study",
      owners: "Homeowner lens",
      renters: "Renter lens",
      controlLabel: "Pathway comparison lens",
      lensLabel: "What this lens emphasizes",
      views: {
        overall: "Compare the full pathway structure against the survey-grounded reference.",
        owners: "Inspect homeowner pathways without exposing social-group labels to the model.",
        renters: "Inspect renter pathways and constraint-sensitive differences using the same measured constructs.",
      },
      note: "Study-design schematic · no unpublished coefficients",
      input: "Persona inputs",
      constructs: "Measured constructs",
      pathways: "Pathway comparison",
      stability: "Repeated-run stability",
    },
    timeline: {
      owner: "Owner",
      renter: "Renter",
      controlLabel: "Household tenure lens",
      lensLabel: "What changes in this lens",
      views: {
        owner: "Owner state includes property adaptation, insurance, damage, payout, and out-of-pocket feedback.",
        renter: "Renter state uses tenure-appropriate choices and financial exposure; property-level actions are not assumed.",
      },
      note: "Illustrative system architecture · not a reported study result",
      start: "Household state",
      choice: "Adaptation choice",
      hazard: "Flood event",
      finance: "Damage, payout, and out-of-pocket update",
      repeat: "Next annual step",
    },
    governance: { controlLabel: "Governance trace state", first: "Inspect proposed action", repaired: "Inspect targeted repair", note: "Frozen demonstration · no live model call", proposal: "Proposed action", parse: "Parser", physical: "Physical check", financial: "Financial check", behavioral: "Behavioral check", audit: "Audit record", update: "State update", failed: "Rejected: cost exceeds available household budget", passed: "Accepted after repair: cost reduced within the declared budget", blocked: "Blocked", accepted: "Accepted" },
  },
  documents: {
    title: "Documents",
    intro: "Choose the document for the context. The website keeps one identity; the PDFs change emphasis for the reader.",
    items: [
      { label: "Industry resume · English", href: "/assets/Wenyu_Chiou_Industry_Resume_EN.pdf", type: "PDF" },
      { label: "Industry resume · 繁中", href: "/assets/Wenyu_Chiou_Industry_Resume_zh-TW.pdf", type: "PDF" },
      { label: "Academic CV · English", href: "/assets/Wenyu_Chiou_Academic_CV_EN.pdf", type: "PDF" },
      { label: "Academic CV · 繁中", href: "/assets/Wenyu_Chiou_Academic_CV_zh-TW.pdf", type: "PDF" },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Build evaluations that connect model behavior to real evidence",
    text: "I am seeking a full-time Summer 2027 internship from approximately late May through mid-August. I am especially interested in LLM evaluation, agent systems, behavioral simulation, and AI for science.",
    email: "wec324@lehigh.edu",
    workAuth: "F-1 student · CPT eligible",
    links: [
      { label: "GitHub", href: "https://github.com/WenyuChiou" },
      { label: "LinkedIn", href: "https://www.linkedin.com/in/wenyu-chiou" },
      { label: "Google Scholar", href: "https://scholar.google.com/citations?user=vSQ3zT4AAAAJ&hl=en" },
      { label: "ORCID", href: "https://orcid.org/0009-0005-8006-1288" },
    ],
  },
  footer: {
    line: "Human-grounded LLM evaluation · governed agents · behavioral simulation",
    note: "Built as a static, accessible research record.",
  },
};
