import esbuild from "esbuild";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import os from "node:os";
import { DEPLOYMENT_CONFIG } from "./deployment-config.mjs";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const tmp = mkdtempSync(path.join(os.tmpdir(), "wy-prerender-"));
const ssrFile = path.join(tmp, "ssr.cjs");

await esbuild.build({
  stdin: {
    contents: [
      'import { renderToString } from "react-dom/server";',
      'import { createElement } from "react";',
      'import { App } from "./app.jsx";',
      'export { SEO } from "./seo.js";',
      'export const renderPage = (page, locale, basePath) => renderToString(createElement(App, { page, locale, basePath }));',
    ].join("\n"),
    resolveDir: ROOT,
    sourcefile: "ssr-entry.jsx",
    loader: "jsx",
  },
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  outfile: ssrFile,
  legalComments: "none",
});

let SEO;
let renderPage;
try {
  ({ SEO, renderPage } = createRequire(import.meta.url)(ssrFile));
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

const esc = (value) => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const jsonLd = (value) => `<script type="application/ld+json">${JSON.stringify(value).replace(/</g, "\\u003c")}</script>`;
const template = readFileSync(path.join(ROOT, "template.html"), "utf8").replace(/\r\n/g, "\n");
const banner = "<!-- GENERATED by prerender.mjs from template.html. Do not edit directly. -->";
const THEME_SCRIPT = 'try{document.documentElement.dataset.theme=localStorage.getItem("wy-theme")||"light"}catch(e){}';
const cspHash = (value) => `'sha256-${createHash("sha256").update(value).digest("base64")}'`;
const aiEndpoint = process.env.PORTFOLIO_AI_ENDPOINT || DEPLOYMENT_CONFIG.aiEndpoint;
const turnstileSiteKey = process.env.TURNSTILE_SITE_KEY || DEPLOYMENT_CONFIG.turnstileSiteKey;
let aiOrigin = "";
try { aiOrigin = aiEndpoint ? new URL(aiEndpoint).origin : ""; } catch { throw new Error("PORTFOLIO_AI_ENDPOINT must be an absolute HTTPS URL"); }
if (aiOrigin && !aiOrigin.startsWith("https://")) throw new Error("PORTFOLIO_AI_ENDPOINT must use HTTPS");

function contentSecurityPolicy(headExtra) {
  const inlineScripts = [...headExtra.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map((match) => match[1]);
  const scriptHashes = [THEME_SCRIPT, ...inlineScripts].map(cspHash).join(" ");
  return [
    "default-src 'self'",
    `script-src 'self' 'wasm-unsafe-eval' ${scriptHashes}${turnstileSiteKey ? " https://challenges.cloudflare.com" : ""}`,
    "style-src 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    `connect-src 'self' https://huggingface.co https://us.aws.cdn.hf.co${aiOrigin ? ` ${aiOrigin}` : ""}`,
    ...(turnstileSiteKey ? ["frame-src https://challenges.cloudflare.com"] : []),
    "worker-src 'self' blob:",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "upgrade-insecure-requests",
  ].join("; ");
}

function extraHead(meta) {
  const fontFiles = meta.locale === "zh-TW"
    ? []
    : ["literata-latin-wght-normal.woff2", "atkinson-hyperlegible-next-latin-wght-normal.woff2"];
  const parts = fontFiles.map((file) => `<link rel="preload" href="/assets/fonts/${file}" as="font" type="font/woff2" crossorigin>`);
  if (meta.page === "home") {
    parts.push('<link rel="preload" href="/assets/agu2025-photo-mobile.webp" as="image" type="image/webp" media="(max-width:620px)" fetchpriority="high">');
    parts.push('<link rel="preload" href="/assets/agu2025-photo.webp" as="image" type="image/webp" media="(min-width:621px)" imagesrcset="/assets/agu2025-photo-tablet.webp 828w, /assets/agu2025-photo.webp 1108w" imagesizes="100vw" fetchpriority="high">');
    parts.push(jsonLd(SEO.person));
  }
  if (SEO.citationMeta.paths.includes(meta.path)) {
    for (const [name, raw] of Object.entries(SEO.citationMeta.tags)) {
      for (const value of Array.isArray(raw) ? raw : [raw]) parts.push(`<meta name="${name}" content="${esc(value)}">`);
    }
    parts.push(jsonLd(SEO.article));
  }
  if (SEO.techArticles[meta.path]) parts.push(jsonLd(SEO.techArticles[meta.path]));
  return parts.map((part) => `  ${part}`).join("\n");
}

const generated = [];
for (const meta of Object.values(SEO.routes)) {
  const appHtml = renderPage(meta.page, meta.locale, meta.basePath);
  if (!appHtml.includes("<h1")) throw new Error(`Route ${meta.path} rendered without an h1`);
  const headExtra = extraHead(meta);
  const english = meta.locale === "en" ? meta.canonical : meta.alternate;
  const chinese = meta.locale === "zh-TW" ? meta.canonical : meta.alternate;
  const values = {
    LANG: meta.lang,
    TITLE: meta.title,
    DESCRIPTION: meta.description,
    CANONICAL: meta.canonical,
    HREFLANG_EN: english,
    HREFLANG_ZH: chinese,
    HREFLANG_DEFAULT: meta.xDefault,
    OG_TYPE: meta.ogType,
    OG_LOCALE: meta.ogLocale,
    OG_IMAGE: SEO.siteUrl + (meta.ogImage || SEO.ogImage.file),
    OG_IMAGE_ALT: meta.page.startsWith("article:") ? meta.title : SEO.ogImage.alt,
    AI_ENDPOINT: aiEndpoint,
    TURNSTILE_SITE_KEY: turnstileSiteKey,
    CSP: contentSecurityPolicy(headExtra),
    HEAD_EXTRA: headExtra,
    THEME_SCRIPT,
    PAGE: meta.page,
    LOCALE: meta.locale,
    BASE_PATH: meta.basePath,
    APP_HTML: appHtml,
  };
  let html = template.replace(/<!-- template\.html[^\n]*-->/, banner);
  for (const [key, raw] of Object.entries(values)) {
    const value = ["APP_HTML", "HEAD_EXTRA", "THEME_SCRIPT"].includes(key) ? raw : esc(raw);
    html = html.replaceAll(`{{${key}}}`, value);
  }
  const leftovers = html.match(/\{\{[A-Z_]+\}\}/g);
  if (leftovers) throw new Error(`Unreplaced placeholders in ${meta.path}: ${leftovers.join(", ")}`);
  const relative = meta.path === "/" ? "index.html" : `${meta.path.slice(1)}index.html`;
  const output = path.join(ROOT, relative);
  mkdirSync(path.dirname(output), { recursive: true });
  writeFileSync(output, html);
  generated.push(relative);
  console.log(`prerendered ${meta.path} -> ${relative}`);
}

console.log(`prerender: ${generated.length} localized routes emitted`);
