import esbuild from "esbuild";
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import os from "node:os";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const tmp = mkdtempSync(path.join(os.tmpdir(), "wy-prerender-"));
const ssrFile = path.join(tmp, "ssr.cjs");

await esbuild.build({
  stdin: {
    contents: [
      'import { renderToString } from "react-dom/server";',
      'import { createElement } from "react";',
      'import { App } from "./app.jsx";',
      'export { SEO } from "./seo.js";',
      'export const renderPage = (page, locale, basePath) => renderToString(createElement(App, { page, locale, basePath }));',
    ].join("\n"),
    resolveDir: ROOT,
    sourcefile: "ssr-entry.jsx",
    loader: "jsx",
  },
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  outfile: ssrFile,
  legalComments: "none",
});

let SEO;
let renderPage;
try {
  ({ SEO, renderPage } = createRequire(import.meta.url)(ssrFile));
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

const esc = (value) => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const jsonLd = (value) => `<script type="application/ld+json">${JSON.stringify(value).replace(/</g, "\\u003c")}</script>`;
const template = readFileSync(path.join(ROOT, "template.html"), "utf8").replace(/\r\n/g, "\n");
const banner = "<!-- GENERATED by prerender.mjs from template.html. Do not edit directly. -->";

function extraHead(meta) {
  const parts = [];
  if (meta.page === "home") {
    parts.push('<link rel="preload" href="/assets/agu2025-photo.webp" as="image" type="image/webp" imagesrcset="/assets/agu2025-photo-mobile.webp 640w, /assets/agu2025-photo.webp 1108w" imagesizes="100vw" fetchpriority="high">');
    parts.push(jsonLd(SEO.person));
  }
  if (SEO.citationMeta.paths.includes(meta.path)) {
    for (const [name, raw] of Object.entries(SEO.citationMeta.tags)) {
      for (const value of Array.isArray(raw) ? raw : [raw]) parts.push(`<meta name="${name}" content="${esc(value)}">`);
    }
    parts.push(jsonLd(SEO.article));
  }
  return parts.map((part) => `  ${part}`).join("\n");
}

const generated = [];
for (const meta of Object.values(SEO.routes)) {
  const appHtml = renderPage(meta.page, meta.locale, meta.basePath);
  if (!appHtml.includes("<h1")) throw new Error(`Route ${meta.path} rendered without an h1`);
  const english = meta.locale === "en" ? meta.canonical : meta.alternate;
  const chinese = meta.locale === "zh-TW" ? meta.canonical : meta.alternate;
  const values = {
    LANG: meta.lang,
    TITLE: meta.title,
    DESCRIPTION: meta.description,
    CANONICAL: meta.canonical,
    HREFLANG_EN: english,
    HREFLANG_ZH: chinese,
    HREFLANG_DEFAULT: meta.xDefault,
    OG_TYPE: meta.ogType,
    OG_LOCALE: meta.ogLocale,
    OG_IMAGE: SEO.siteUrl + SEO.ogImage.file,
    OG_IMAGE_ALT: SEO.ogImage.alt,
    HEAD_EXTRA: extraHead(meta),
    PAGE: meta.page,
    LOCALE: meta.locale,
    BASE_PATH: meta.basePath,
    APP_HTML: appHtml,
  };
  let html = template.replace(/<!-- template\.html[^\n]*-->/, banner);
  for (const [key, raw] of Object.entries(values)) {
    const value = key === "APP_HTML" || key === "HEAD_EXTRA" ? raw : esc(raw);
    html = html.replaceAll(`{{${key}}}`, value);
  }
  const leftovers = html.match(/\{\{[A-Z_]+\}\}/g);
  if (leftovers) throw new Error(`Unreplaced placeholders in ${meta.path}: ${leftovers.join(", ")}`);
  const relative = meta.path === "/" ? "index.html" : `${meta.path.slice(1)}index.html`;
  const output = path.join(ROOT, relative);
  mkdirSync(path.dirname(output), { recursive: true });
  writeFileSync(output, html);
  generated.push(relative);
  console.log(`prerendered ${meta.path} -> ${relative}`);
}

console.log(`prerender: ${generated.length} localized routes emitted`);
