export const COPY = {
  en: {
    stages: ['Human evidence', 'Context', 'LLM proposal', 'Validation / repair', 'Consequence'], agent: 'Agent decision',
    synthetic: 'Synthetic example', pause: 'Pause scene animation', play: 'Play scene animation', reset: 'Reset scene',
    modes: { direction: 'Direction', groups: 'Subgroups', repeats: 'Stability' }, mode: 'Comparison mode',
    human: 'Human reference', model: 'Model choices', compare: 'Paired comparison',
    record: 'Record', group: 'Group', reference: 'Reference', runs: 'Model runs', yes: 'Act', no: 'Wait',
    rowLabels: { low: 'Low efficacy', high: 'High efficacy', A: 'Group A', B: 'Group B', run1: 'Run 1', run2: 'Run 2', run3: 'Run 3' },
    findings: { direction: 'The direction reverses: higher efficacy predicts action in the reference, but inaction in model choices.', groups: 'The same overall total conceals different choices in groups A and B.', repeats: 'Totals stay constant while individual choices switch between runs.' },
    units: 'Action counts in authored fixtures; not study estimates.', pair: 'Select a paired record',
    proposal: 'Structured proposal', gate: 'Validation gate', state: 'System state',
    repair: 'Repair and revalidate', repaired: 'Repair accepted', blocked: 'Rejected · state unchanged', accepted: 'Accepted · state updated',
    checks: ['Format', 'Permission', 'Budget'], pass: 'Pass', fail: 'Fail',
    action: 'Protect contents', cost: 'Requested resources', remaining: 'Available resources',
    protection: 'Contents protection', inactive: 'Not applied', active: 'Applied', budgetError: '9 requested, 6 available. Only the cost field needs repair.',
    repairedNote: 'Cost repaired to 2. All checks passed before resources changed from 6 to 4.',
    unitsGov: 'Resource tokens are illustrative, not currency.',
    owner: 'Homeowner', renter: 'Renter', tenure: 'Household tenure', household: 'Household', environment: 'River hazard', resources: 'Resources',
    barrier: 'Install a temporary barrier', contents: 'Move belongings to safety',
    ownerLimit: 'A homeowner can protect the building; the river hazard stays unchanged.', renterLimit: 'A renter can move belongings, not elevate the building. The river hazard stays unchanged.',
    hazard: 'Hazard level', tokens: 'Resource tokens', unchanged: 'Unchanged by household action',
    syntheticUnits: 'Levels and tokens are synthetic units; not FLOODABM outputs.',
    simulationStep: ['Interpret the hazard signal.', 'Tenure and resources constrain the options.', 'Choose an allowed household action.', 'Check permission and available resources.', 'Apply the action; carry remaining resources into the next cycle.'],
    staticTitle: 'Decision flow and sources', publicSource: 'Research evidence', staticNotice: 'Interactive controls require JavaScript. The complete flow and sources remain below.',
  },
  'zh-TW': {
    stages: ['人類證據', '決策情境', 'LLM 提案', '驗證／修正', '系統後果'], agent: '代理決策',
    synthetic: '合成示例', pause: '暫停場景動畫', play: '播放場景動畫', reset: '重設場景',
    modes: { direction: '方向', groups: '群體', repeats: '穩定性' }, mode: '比較方式',
    human: '人類參考', model: '模型選擇', compare: '配對比較', record: '紀錄', group: '群體', reference: '參考選擇', runs: '模型重複選擇', yes: '行動', no: '等待',
    rowLabels: { low: '低效能感', high: '高效能感', A: 'A 群體', B: 'B 群體', run1: '第 1 次', run2: '第 2 次', run3: '第 3 次' },
    findings: { direction: '方向相反：參考紀錄中，效能感較高者採取行動；模型的選擇卻相反。', groups: '相同的整體總數，掩蓋了 A、B 群體內不同的選擇。', repeats: '每次總數不變，個別紀錄的選擇卻在重複執行間切換。' },
    units: '數值為合成紀錄的行動次數，不是研究估計值。', pair: '選擇配對紀錄',
    proposal: '結構化提案', gate: '驗證閘門', state: '系統狀態', repair: '修正並重新驗證', repaired: '修正已通過', blocked: '已拒絕・狀態未變', accepted: '已通過・狀態已更新',
    checks: ['格式', '權限', '資源'], pass: '通過', fail: '未通過', action: '保護室內財物', cost: '提案所需資源', remaining: '可用資源', protection: '財物保護', inactive: '尚未套用', active: '已套用',
    budgetError: '要求 9 單位，可用 6 單位；只需修正資源欄位。', repairedNote: '所需資源修正為 2；全部驗證通過後，可用資源才由 6 更新為 4。', unitsGov: '資源代幣僅供示意，並非貨幣。',
    owner: '屋主', renter: '租客', tenure: '住戶身分', household: '住戶', environment: '河流危害', resources: '資源', barrier: '設置臨時防水擋板', contents: '將財物移至安全處',
    ownerLimit: '屋主可保護建物，但不會因此改變河流危害。', renterLimit: '租客可搬移財物，不能自行抬高建物；河流危害也不會因此改變。',
    hazard: '危害等級', tokens: '資源代幣', unchanged: '不受住戶行動影響', syntheticUnits: '等級與代幣為合成單位，並非 FLOODABM 模型輸出。',
    simulationStep: ['理解危害訊號。', '住戶身分與資源限制可行選項。', '選擇有權採取的住戶行動。', '檢查行動權限與可用資源。', '套用行動，將剩餘資源帶入下個循環。'],
    staticTitle: '決策流程與來源', publicSource: '研究證據', staticNotice: '互動操作需要 JavaScript；完整流程與來源仍列於下方。',
  },
};
