export const FLOOD_LABELS = {
  en: {
    title: "One household. Different ways to respond.", synthetic: "Synthetic scenario",
    intro: "Inspect where a household action takes effect, and what it leaves unchanged.",
    scenario: "Flood scenario", moderate: "Moderate", severe: "Severe", tenure: "Household tenure", owner: "Homeowner", renter: "Renter",
    action: "Proposed action", hold: "No measure", prepare: "Prepare", insure: "Insure", elevate: "Elevate",
    apply: "Apply action", reset: "Reset scenario", activate: "Explore in 3D", loading: "Loading scene", failed: "3D is unavailable. The diagram and controls remain available.", retry: "Try 3D again",
    comparison: "Compare states", baseline: "Before action", appliedView: "Applied action", objects: "Inspect an element",
    household: "Household", river: "River", neighbors: "Neighbors", overview: "Overview", view: "Viewpoint",
    rotateLeft: "Rotate left", rotateRight: "Rotate right", resetCamera: "Reset viewpoint",
    diagram: "Schematic river and households", diagramDescription: "A fixed neighborhood beside a river. Actions change the focal household, not the river or its neighbors.",
    context: "Scenario", current: "Visible action", physical: "Physical measure", insurance: "Insurance status", included: "Selected", absent: "Not selected",
    assumptions: "Assumptions and sources", boundary: "This is a teaching scene, not a FLOODABM run. Drawing units are relative; no flood depths, financial losses, payouts, or forecasts are calculated.",
    source: "Public FLOODABM repository", methodology: "Methods and public evidence remain in the case study.",
    ready: "No measure is applied.", draft: "Proposed action changed. The applied state is unchanged.", applied: "Action applied.", ownerOnly: "Structural elevation is available only to homeowners in this example.", invalid: "This selection is unavailable. The applied state is unchanged.",
    explanations: {
      household: "Preparation and structural elevation act at the selected home. Insurance changes coverage, not physical exposure.",
      river: "The river responds only to the selected flood scenario. A household action does not lower the river.",
      neighbors: "Neighboring homes remain unchanged. This scene does not model spillovers or collective adaptation.",
    },
  },
  "zh-TW": {
    title: "同一個住戶，不同的應對方式。", synthetic: "合成情境",
    intro: "檢視住戶行動作用在哪裡，以及哪些部分不會隨之改變。",
    scenario: "洪水情境", moderate: "中度", severe: "嚴重", tenure: "居住身分", owner: "屋主", renter: "租屋者",
    action: "擬採行動", hold: "不採措施", prepare: "預先準備", insure: "投保", elevate: "抬升住宅",
    apply: "套用行動", reset: "重設情境", activate: "開啟 3D", loading: "正在載入場景", failed: "目前無法顯示 3D，仍可使用平面圖與操作選項。", retry: "重新載入 3D",
    comparison: "比較狀態", baseline: "行動前", appliedView: "已套用行動", objects: "檢視元素",
    household: "住戶", river: "河道", neighbors: "鄰近住宅", overview: "總覽", view: "觀察視角",
    rotateLeft: "向左旋轉", rotateRight: "向右旋轉", resetCamera: "重設視角",
    diagram: "河道與住戶示意圖", diagramDescription: "河道旁的固定住宅群。行動只影響焦點住戶，不改變河道或鄰近住宅。",
    context: "目前情境", current: "顯示的行動", physical: "物理措施", insurance: "投保狀態", included: "已選擇", absent: "未選擇",
    assumptions: "假設與來源", boundary: "這是教學示意場景，不是 FLOODABM 模擬。繪圖採相對單位，不計算洪水深度、財務損失、保險給付或預測。",
    source: "FLOODABM 公開儲存庫", methodology: "研究方法與公開證據保留在本案例中。",
    ready: "目前未套用措施。", draft: "擬採行動已變更，已套用狀態保持不變。", applied: "已套用行動。", ownerOnly: "此示例僅允許屋主抬升住宅結構。", invalid: "目前無法使用這個選項，已套用狀態保持不變。",
    explanations: {
      household: "預先準備與結構抬升作用於焦點住宅；投保改變承保狀態，不改變物理暴露。",
      river: "河道只隨所選洪水情境改變，個別住戶行動不會降低河流水位。",
      neighbors: "鄰近住宅保持不變；此場景不模擬外溢效果或集體調適。",
    },
  },
};
